### ISSUE TITLE
GeometryWidget: support all geometry types

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-gui#10]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/issues/10)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
As of [pull request #50](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/pull-requests/50), `GeometryWidget` supports `box`, `cylinder`, `sphere` and `mesh`. We should support all types in [ignition::msgs::Geometry](https://github.com/ignitionrobotics/ign-msgs/blob/affd08b7f51ffa2c7c90d13201e00999459bd0ec/ignition/msgs/geometry.proto#L40).

**Comment by chapulina** [comment]
This refers to `ign-gui0`, which is no longer receiving new features.
