### ISSUE TITLE
Consider using Qt's plugin framework instead of ignition's

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-gui#11]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/issues/11)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
Qt provides its own [plugin framework](http://doc.qt.io/qt-5/plugins-howto.html). It might be a good idea to use that instead of Ignition Common's, since in theory it is especially tailored for Qt.

There is some urgency sorting this out since there is a [pull request](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-common/pull-requests/73/slimmed-down-the-plugin-pull-request-no/diff) landing into ign-common's default branch soon which will break compatibility with Ignition GUI.

Some things to be figured out:

* Does Qt provide the same features as Ignition, such as:
    * Cross-platform support (yes)
    * Automatically unloading libraries when they are no longer in use (might require some work on our end?)
    * Libraries / plugins may offer more than one interface (looks like a yes)
    * Can discover / find new plugins at runtime (looks like a yes)

* How much effort would it be to support the ign-gui case with ign-common's new plugin loader? Is it worth the trouble?

@mxgrey

**Comment by chapulina** [comment]
Ignition plugin has been working well for us, so closing.
