### ISSUE TITLE
Merge Image Display UpdateFrom* functions.

### ISSUE THREAD

**Issue by iche033** [ignitionrobotics/ign-gui#177]
## Desired behavior
There is quite a bit of duplicate code in the various UpdateFrom* functions in Image Display. Let's try to keep the same Image Display behavior and functionality but with some refactoring underneath the hood. 

## Implementation suggestion
Merge the `UpdateFrom*` function. We could templates or just refactor out the code from converting an image array of the input type (int8, int16, float32) to an rgb image buffer:
https://github.com/ignitionrobotics/ign-gui/blob/ign-gui4/src/plugins/image_display/ImageDisplay.cc#L261-L280

## Additional context
related pull request [comment](https://github.com/ignitionrobotics/ign-gui/pull/176#discussion_r571064185)

**Comment by adlarkin** [comment]
I'm closing this since #212 has been merged.
