### ISSUE TITLE
[Plot] Remove hardcoded time on x axis

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-gui#18]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/issues/18)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
See widgets introduced on [pull request #81](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/pull-requests/81)

**Comment by chapulina** [comment]
This issue refers to `ign-gui0`, which is no longer receiving new features. So I'll close this.

But this is something to keep in mind for the plotting tool under development for Ignition Dome, FYI @AmrElsersy .
