### ISSUE TITLE
Sporadic UNIT_VariablePillContainer_TEST failure

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-gui#19]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/issues/19)) by Nate Koenig (Bitbucket: [Nathan Koenig](https://bitbucket.org/%7Bc862cdd9-fcc8-4419-9fc7-e20db14b8fcb%7D/)).**

----------------------------------------
This test mentioned in the title fails about 4 out of 10 times for me. Here is the output:

```
/data/ignition/ign-gui/src/VariablePillContainer_TEST.cc:185: Failure
Value of: var02->mapToGlobal(varCenter).y()
  Actual: 52
Expected: var02Global.y()
Which is: 15
```

**Comment by chapulina** [comment]
This refers to `ign-gui0`, which is no longer under development. Closing.
