### ISSUE TITLE
Can't scroll to newly added plugin

### ISSUE THREAD

**Issue by jennuine** [ignitionrobotics/ign-gui#200]
## Environment
* OS Version: Ubuntu 20.04 
* Source or binary build?
  
  
Source, `main` branch, latest commit 5555853ce9ad2ae15860c2d3fc7f79e12247940a

## Description
* Expected behavior: Scroll to the newly added plugin on the righthand pane
* Actual behavior: Can't scroll until the window has been resized

Most likely introduced by https://github.com/ignitionrobotics/ign-gui/pull/194

## Steps to reproduce

1. `ign gazebo shapes.sdf`
2. Click any plugin from the menu bar
3. Attempt to scroll

## Output

![Peek 2021-03-25 15-37](https://user-images.githubusercontent.com/8602001/112553190-41d97500-8d81-11eb-92a5-3d1b7adf856b.gif)

**Comment by chapulina** [comment]
This corner case was overlooked in #194. 

When fixing this, we should make sure we don't break the use cases that were fixed then:

* If the window is not large enough to fit all plugins, squish them all to their minimum height and make the split scrollable.
* If the window is large enough to fit all plugins, they are stretched to fill the entire height, and their proportion can be changed dragging the separator.
* Collapsed plugins behave consistently with the above
* Adding / removing plugins also behaves as expected
