### ISSUE TITLE
MessageWidget's widget removal failing on OSX

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-gui#23]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/issues/23)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
The test fails as follows:

~~~
23: /Users/jenkins/workspace/ignition_gui-ci-pr_any-homebrew-amd64/ign-gui/src/MessageWidget_TEST.cc:1034: Failure
23: Value of: widget->PropertyWidgetCount()
23:   Actual: 22
23: Expected: count
23: Which is: 15
~~~

**Comment by chapulina** [comment]
This refers to `ign-gui0`, which is no longer under development. Closing.
