### ISSUE TITLE
Fail to find Plot plugin as child of window in OSX

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-gui#24]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/issues/24)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
`Plot_TEST` has been failing on OSX because it fails to find `Plot` as child of the main window, even though debug statements indicate the plugin was properly loaded. 

I don't have a way to immediately test this on OSX to check if the plugin itself works, so I'm skipping the tests for now until this can be investigated.

**Comment by chapulina** [comment]
This refers to `ign-gui0`, which is no longer under development. Closing.
