### ISSUE TITLE
Native QFileDialogs in Ubuntu Bionic don't have a QLineEdit

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-gui#28]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/issues/28)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
And tests that relied on that fail.

![bionicfiledialog.png](https://osrf-migration.github.io/ignition-gh-pages/data/bitbucket.org/repo/64K5zaR/images/534940688-bionicfiledialog.png)

~~~
/mnt/TERA/code/ign-gui/src/GeometryWidget_TEST.cc:144: Failure
Expected: (edits.size()) > (0), actual: 0 vs 0
~~~

**Comment by chapulina** [comment]
This refers to `ign-gui0`, which is no longer under development. Closing.
