### ISSUE TITLE
[MessageWidget] Repeated field name doesn't handle name changes

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-gui#29]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/issues/29)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
The feature added on [pull request #109](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/pull-requests/109) only works nicely if all subsequent messages maintain the number of repetitions, their order and their names. If either of these changes, the collapsible is not renamed and the widget becomes inconsistent.

A failing test case has been added and commented out. Possible solutions I can think of:

1. Never reuse repeated widgets, always construct them new - this is very expensive computationally
2. Always check the name and rename the widget if needed - this should be cheaper than #1 but will still have some impact

**Comment by chapulina** [comment]
This refers to `ign-gui0`, which is no longer under development. Closing.
