### ISSUE TITLE
Failed to copy versioned gui.config file

### ISSUE THREAD

**Issue by ahcorde** [ignitionrobotics/ign-gui#294]
I have removed `~/.ignition/gui/gui.config` I would expect to get the new version of the `gui.config` there. But I'm getting this error:

```sh
[GUI] [Err] [Gui.cc:269] Failed to copy installed config [/home/ahcorde/ignition_fortress/install/share/ignition/ignition-gazebo6/gui/gui.config] to default config [/home/ahcorde/.ignition/gazebo/6/gui.config].
```

`ign-gazebo` is not able to create the right versioned folder.

**Comment by chapulina** [comment]
Fix in https://github.com/ignitionrobotics/ign-gazebo/pull/1070
