### ISSUE TITLE
MinimalScene: configurable near/far clip planes

### ISSUE THREAD

**Issue by scpeters** [ignitionrobotics/ign-gui#308]
## Desired behavior

Configuration of the clipping distance for the near/far clip planes was requested in https://github.com/osrf/gazebo/issues/2064. Support was added for configuring these parameters via the gzclient GUI in [BitBucket pull request 2470](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/pull-requests/2470), though support for setting the parameter via a world file was requested but not implemented.

I request that we add the near/far clipping distance as parameters for the MinimalScene camera.

## Alternatives considered

The parameters could be configured interactively via a GUI widget or an ignition-transport interface, but I would prefer specifying it in XML.

## Implementation suggestion

The following is an example of the current XML configuration parameters for a `MinimalScene` plugin instance:
~~~
    <plugin filename="MinimalScene">
      <engine>ogre</engine>
      <scene>banana</scene>
      <ambient_light>1.0 0 0</ambient_light>
      <background_color>0 1 0</background_color>
      <camera_pose>1 2 3 0 0 1.57</camera_pose>
    </plugin>
~~~

I would propose adding the following parameters to mirror the SDFormat camera clipping distance parameter structure:

~~~
      <camera_clip>
        <near>0.1</near>
        <far>5000</far>
      </camera_pose>
~~~

~~~
    <plugin filename="MinimalScene">
      <engine>ogre</engine>
      <scene>banana</scene>
      <ambient_light>1.0 0 0</ambient_light>
      <background_color>0 1 0</background_color>

      <camera_clip>
        <near>0.1</near>
        <far>5000</far>
      </camera_pose>

      <camera_pose>1 2 3 0 0 1.57</camera_pose>
    </plugin>
~~~

## Additional context

Although setting these parameters from SDFormat was never implemented in gazebo, a Gazebo plugin for this purpose was created in the following public repository:

* https://github.com/nasa/irg_open/tree/ros2/irg_gazebo_plugins/src/IRGNearFarClipPlugin

**Comment by scpeters** [comment]
I've added the Fortress label since `MinimalScene` as added in fortress

**Comment by chapulina** [comment]
> a Gazebo plugin for this purpose was created in the following public repository:

Another reference, the SimSlides plugin also has an implementation for both Gazebo classic and Ignition:

https://github.com/chapulina/simslides/blob/1dcd393fb9622043cdf90c68ade8e8af5d48195c/common/Common.cc#L24-L35

**Comment by jennuine** [comment]
PR #309 allows you to configure near/far clip distance in xml. Should I work on extending ign-gazebo's view angle plugin to configure it through the GUI?

**Comment by scpeters** [comment]
> PR #309 allows you to configure near/far clip distance in xml. Should I work on extending ign-gazebo's view angle plugin to configure it through the GUI?

sounds good to me 👍

**Comment by iche033** [comment]
related issue: https://github.com/ignitionrobotics/ign-gazebo/issues/1154
