### ISSUE TITLE
Display plugins meta-ticket

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-gui#31]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/issues/31)) by Deanna Hood (Bitbucket: [d_hood](https://bitbucket.org/%7B40d490b4-7de9-4c89-ac1c-2219a22057eb%7D/)).**

----------------------------------------
Objective is a widget that lets you load various "displays" (something that paints on the render window, e.g. a grid). Each display will have some common properties (e.g. checkbox for toggling visibility), and potentially some custom properties specific to its plugin (e.g. colour of a grid).

Subtasks:

- [✔] [#137](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/pull-requests/137) DisplayPlugin base class, sample displays (grid, realtime factor), and minimal loader. Minimum functionality, not the most "beautiful" widget.
    - Limitations:
        - Piggybacking on loading of generic Plugins.
        - The list of displays to load can be specific in the config file, but not the configuration of the displays.
        - RealtimeFactorDisplay using MoveableText instead of an overlay of some form.
    - Issues:
        - [✔] Displays widget's layout (displays not aligning to top, not expanding correctly).
        - [✔] Correct size of Displays widget when using DisplayPlugins with expandable properties, e.g. displays can expand beyond the bottom of the screen. Should use scroll area,  see [#32](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/issues/32) (#32).
        - [✔ ] RealtimeFactorDisplay disable not working.
        - [✔] RealtimeFactorDisplay crash on initialisation in some demos.
- [✔] [#144](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/pull-requests/144) Custom Plugin type/loading (so DisplayPlugins don't pollute the list of Plugins available).
- [✔] [#143](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/pull-requests/143) Call SetVisible on each display's root Visual when visibility checkbox is toggled (needs to be implemented in ign-rendering: [#69](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-rendering/pull-requests/69) ✔).
- [✔] [#146](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/pull-requests/146) UI enhancements
- [✔] [#148](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/pull-requests/148) Loading initial properties of displays from config file.
- [✔] [#148](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/pull-requests/148) Saving/loading configuration of Displays widget.
- [ ] [#150](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/pull-requests/150) RTF Display using/mimicking Overlay instead of MoveableText. (Requires ability to attach visuals to camera in ign-rendering: [#88](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-rendering/pull-requests/88) ✔)
- [ ] Implement OriginDisplay (available downstream)

**Comment by chapulina** [comment]
This ticket refers to `ign-gui0`, which is no longer under development, so I'll close it. But it could be a good reference to the `ign-rviz` work that @Sarath18 is doing. CC @ahcorde .

Here's the `DisplayPlugin` base class: https://github.com/ignitionrobotics/ign-gui/blob/ign-gui0/include/ignition/gui/DisplayPlugin.hh
