### ISSUE TITLE
What is the planned relationship between MinimumScene and TransportSceneManager?

### ISSUE THREAD

**Issue by Levi-Armstrong** [ignitionrobotics/ign-gui#358]
I noticed that MinimumScene has the following, but then I came across TransportSceneManager which seems to manage the same set of topics and service. Is the plan that this functionality will be removed from MinimumScene and TransportSceneManager should be used going forward or is there another intended purpose of TransportSceneManager?

``` c++
    /// \brief Scene service. If not empty, a request will be made to get the
    /// scene information using this service and the renderer will populate the
    /// scene based on the response data
    public: std::string sceneService;

    /// \brief Scene pose topic. If not empty, a node will subcribe to this
    /// topic to get pose updates of objects in the scene
    public: std::string poseTopic;

    /// \brief Ign-transport deletion topic name
    public: std::string deletionTopic;

    /// \brief Ign-transport scene topic name
    /// New scene messages will be published to this topic when an entities are
    /// added
    public: std::string sceneTopic;
```

**Comment by ahcorde** [comment]
I think these methods and attributes are there for some historical reason. Because are not used at all. I created a [PR](https://github.com/ignitionrobotics/ign-gui/pull/359) to remove then

**Comment by Levi-Armstrong** [comment]
Thank you for the support.
