### ISSUE TITLE
Allow docked qtquick to collapse

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-gui#36]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/issues/36)) by Nate Koenig (Bitbucket: [Nathan Koenig](https://bitbucket.org/%7Bc862cdd9-fcc8-4419-9fc7-e20db14b8fcb%7D/)).**

----------------------------------------
It would be nice to allow docked qtquick widgets to collapse. For example, a user may have many docked widgets but only wants 1 fully expanded.

**Comment by chapulina** [comment]
I ended up duplicating this on #74 . I'll close this one since that one now has more comments.
