### ISSUE TITLE
Close plugin menu after a plugin has been added

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-gui#37]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/issues/37)) by Nate Koenig (Bitbucket: [Nathan Koenig](https://bitbucket.org/%7Bc862cdd9-fcc8-4419-9fc7-e20db14b8fcb%7D/)).**

----------------------------------------
# Summary

After inserting a plugin using the drop-down menu in the QTQuick version of ign-gui, I would expect the drop-down to close. Right now the menu stays open, and the user has to click away to close the menu.

# Motivation

I think it feels more natural for the drop-down menu to close after a plugin has been inserted. The downside is that a user who wants to insert multiple plugins will need to click the drop-down menu multiple times.

# Describe alternatives you've considered

We could keep the current behavior, where the menu stays open after a plugin is clicked. However, I think it's more likely that a user wants to insert a single plugin rather than multiple at any one time.

# Additional context

![drop-down-menu.gif](https://osrf-migration.github.io/ignition-gh-pages/data/bitbucket.org/repo/64K5zaR/images/2809944877-drop-down-menu.gif)

**Comment by chapulina** [comment]
Merged to Dome in #60.
