### ISSUE TITLE
gz11 - Missing: ignition-rendering1 (Components: ogre)

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-gui#38]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/issues/38)) by Pei JIA (Bitbucket: [jiapei100](https://bitbucket.org/%7B18260a78-aa91-4162-bcbb-4faf42e302fb%7D/)).**

----------------------------------------
1) I successfully installed Ogre2.x (NOT Ogre1.x) . 
```console
➜  pkgconfig ll ignition-rendering1*
-rw-r--r-- 1 root root 384 Jan 31 05:24 ignition-rendering1-ogre2.pc
-rw-r--r-- 1 root root 384 Jan 31 05:24 ignition-rendering1.pc
➜  pkgconfig pwd
/usr/local/lib/pkgconfig
➜  pkgconfig 
```

2) However, still failed to build **ign-gui**, with the following **ERROR** message:
```console
-- BUILD ERRORS: These must be resolved before compiling.
 -- Missing: ignition-rendering1 (Components: ogre)
 -- END BUILD ERRORS

 CMake Error at /usr/local/share/cmake/ignition-cmake2/cmake2/IgnConfigureBuild.cmake:66 (message):
   Errors encountered in build.  Please see BUILD ERRORS above.
 Call Stack (most recent call first):
   CMakeLists.txt:124 (ign_configure_build)
```

Did anybody meet the same issue? How to successfully build **ign-gui (gz11)** with **Ogre2.x** and without **Ogre1.x** ?

**Comment by chapulina** [comment]
The `gz11` branch is very outdated. I'll close this, please open a new issue if a similar issue comes up.
