### ISSUE TITLE
Example config pubsub is broken

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-gui#39]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/issues/39)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
# Description

The example [pubsub.config](https://github.com/ignitionrobotics/ign-gui/blob/d7865bfdd1277d88cac9d9c4167a27824bfb765c/examples/config/pubsub.config) is broken. It is currently [disabled from testing](https://github.com/ignitionrobotics/ign-gui/blob/d7865bfdd1277d88cac9d9c4167a27824bfb765c/test/integration/Examples_TEST.cc#L43:45) in `INTEGRATION_Examples_TEST`; otherwise it causes a seg-fault.

# Steps to reproduce

Apply the following patch, build and run the test, which will only test the `pubsub.config`:

~~~
diff -r 83190ef569c4b4871bc1afa039232ddd5317d661 test/integration/Examples_TEST.cc
--- a/test/integration/Examples_TEST.cc	Thu Mar 07 11:14:34 2019 -0800
+++ b/test/integration/Examples_TEST.cc	Thu Mar 07 13:30:12 2019 -0800
@@ -40,9 +40,9 @@
   ignition::common::DirIter endIter;
   for (common::DirIter file(exampleConfigPath); file != endIter; ++file)
   {
-    // TODO(louise) Investigate why TopicEcho crashes on shutdown
-    if ((*file).find("pubsub") != std::string::npos)
-      return;
+    // only test pubsub.config to observe failure
+    if ((*file).find("pubsub") == std::string::npos)
+      continue;
 
     Application app(g_argc, g_argv);
     app.AddPluginPath(std::string(PROJECT_BINARY_PATH) + "/lib");
~~~

**Expected behavior:**  

test passes

**Actual behavior:**

test fails

**Reproduces how often:** 

100% of time

# Versions

1.0.0

**Comment by chapulina** [comment]
I just checked that the `pubsub.config` example is working at runtime and the test also passes without crashing:

```
[GUI] [Msg] Loading config [/home/chapulina/citadel_ws/src/ign-gui/examples/config/pubsub.config]
[GUI] [Dbg] [Application.cc:305] Loading plugin [Publisher]
[GUI] [Msg] Added plugin [Publisher] to main window
[GUI] [Msg] Loaded plugin [Publisher] from path [/home/chapulina/citadel_ws/build/ignition-gui3/lib/libPublisher.so]
[GUI] [Dbg] [Application.cc:305] Loading plugin [TopicEcho]
[GUI] [Msg] Added plugin [Topic echo] to main window
[GUI] [Msg] Loaded plugin [TopicEcho] from path [/home/chapulina/citadel_ws/build/ignition-gui3/lib/libTopicEcho.so]
[GUI] [Dbg] [Application.cc:266] Loading window config
[GUI] [Dbg] [Application.cc:421] Applying config
[GUI] [Dbg] [Application.cc:130] Terminating application.
[GUI] [Dbg] [Application.cc:87] Initializing application.
[GUI] [Dbg] [Application.cc:407] Create main window
```
