### ISSUE TITLE
Notification snackbar

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-gui#44]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/issues/44)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
# Summary

We often want to display information to users, and ideally that would be displayed in a unified way across the app. On material design terms, we should have a [snackbar](https://material.io/components/snackbars/#anatomy).

# Motivation

Many plugins will want to display some text information to users, such as errors, warnings and other information. But if each plugin displays it in a different way, the user's experience is not as fluid. Having a central snackbar that can receive notifications from any plugin would be ideal.

# Describe alternatives you've considered

Currently, plugins are either displaying all their notifications on the console, or [opening dialogs](https://github.com/ignitionrobotics/ign-gui/blob/88a1c4c12c7235cf45b1c4e19b4bbca0b8353f17/include/ignition/gui/qml/Main.qml#L278).

# Additional context

Additional references:

* Angular material's [snackbar](https://material.angular.io/components/snack-bar/overview)
* Polymer's [toast](https://www.webcomponents.org/element/@polymer/paper-toast/demo/demo/index.html)

**Comment by ahcorde** [comment]
Related PRs 
  - https://github.com/ignitionrobotics/ign-gui/pull/369
  - https://github.com/ignitionrobotics/ign-gui/pull/370
