### ISSUE TITLE
Undocked plugins have transparent background

### ISSUE THREAD

**Issue by Sarath18** [ignitionrobotics/ign-gui#61]
Plugins in the main window, when undocked, have a transparent background which makes them less readable if they in front of some other plugin.
There are two possible implementations in my mind to solve them:
1. Adding a color palette on the floating plugin toolbar. User can select the background color along with the transparency.
2. Adding color palette with the transparency in plugin settings (right click -> settings).

The color palette option in the toolbar is easily accessible and noticeable but on the other hand color palette placed in the settings menu seems like the right way to do. I would like inputs on this issue to go ahead with the actual implementation.

**Comment by chapulina** [comment]
+1 to color palette on the plugin settings menu, this is something that has come to mind before. Thanks!
