### ISSUE TITLE
Plotting tool

### ISSUE THREAD

**Issue by chapulina** [ignitionrobotics/ign-gui#66]
Gazebo-classic has a featureful [plotting tool](https://www.youtube.com/watch?v=G5qBaEXpkvE) so users can visualize various types of data coming from simulation.

We initially ported that tool to Ignition back in [ign-gui0](https://github.com/ignitionrobotics/ign-gui/tree/ign-gui0/src/plugins/plot), when we were still using `QWidgets`. Since we moved to [QML](https://doc.qt.io/qt-5/qtqml-index.html), we need a new plotting tool using [QML's QtCharts](https://doc.qt.io/qt-5/qtcharts-qmlmodule.html).

# User stories

Here are some user stories ordered from the most important to the least important. The users are defined as follows:

* **ign-gui user**: someone running an application built on top of Ignition GUI which they didn’t necessarily write themselves
* **ign-gazebo user**: someone running a simulation which they didn’t necessarily write themselves. All `ign-gazebo` users are `ign-gui` users.
* **ign-gui developer**: someone writing new `ign-gui` plugins
* **ign-gazebo developer**: someone writing new `ign-gazebo` plugins. Some `ign-gazebo` developers are also `ign-gui` developers (if they write `ign-gazebo` GUI plugins).

Some stories:

1. As an ign-gazebo user, I want to plot the X position of my robot over sim time
1. As an ign-gazebo user, I want to plot the acceleration data of my robot's IMU
1. As an ign-gazebo user, I want to plot the angular velocities of all my robot’s wheels on the same plot
    1. I want to add new variables to an existing plot
    1. I want to remove variables from an existing plot
1. As an ign-gazebo user, I want to different plots side-by-side
1. As an ign-gazebo user, I want to be able to zoom into a plot
1. As an ign-gui developer, I want to plot the value of an Ignition Transport topic over time
1. As an ign-gazebo user, I want to plot the value of a built-in component over time
1. As an ign-gazebo developer, I want to plot the value of a custom component over time
1. As an ign-gui user, I want to hover over a plot and see the exact value at that point
1. As an ign-gui user, I want to clear the current values in a plot
1. As an ign-gui user, I want to export a plot as a CSV file to process it with a different application
1. As an ign-gui user, I want to export a plot as a SVG file to display it on a presentation

# Features

Based on the user stories above, here's a list of features to be implemented:

## Ignition GUI

These features should be implemented on Ignition GUI, so they can be used by users that are not using Ignition Gazebo.

- [ ] Plot messages and fields from ign-transport topics
    * User stories: 2, 6
- [ ] List all topics and their “plottable” fields #69 
    * User stories: 3
- [ ] Add new variables to a plot, choosing from list
    * User stories: 3
- [ ] Remove variables from a plot
    * User stories: 3
- [ ] Multiple plot plugins can be instantiated at the same time
    * User stories: 4
- [ ] Zoom
    * User stories: 5
- [ ] Hover line and value
    * User stories: 9
- [ ] Clear plot
    * User stories: 10
- [ ] Export to CSV
    * User stories: 11
- [ ] Export to SVG
    * User stories: 12

## Ignition Gazebo

Additional features that are only needed in Ignition Gazebo.

> Keeping track of them here just to have it all in one place.

- [ ] List all components and their “plottable” fields (leverage [Component Inspector](https://ignitionrobotics.org/docs/citadel/manipulating_models#component-inspector))
    * User stories: 1, 3, 7, 8
- [ ] Plot ign-gazebo components
    * User stories: 1, 3, 7, 8

# Implementation

@AmrElsersy has started implementation at https://github.com/AmrElsersy/Ignition-plotting. That will be refactored and moved to `ign-gazebo` / `ign-gui`.

The current plan is to split the implementation into a few parts:

* Ignition GUI
    * - [ ] **TopicViewer**: An `ign-gui` plugin which lists all `ign-transport` topics currently published. #69
        * It's the same idea as `ign-gui0`'s [TopicViewer](https://github.com/ignitionrobotics/ign-gui/blob/ign-gui0/include/ignition/gui/plugins/TopicViewer.hh), see [this PR](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/pull-requests/15/page/1):
            ![4211734814-topic_viewer](https://user-images.githubusercontent.com/5751272/83197321-29adb080-a0f2-11ea-817c-774aaa494024.png)
        * It's a regular `ign-gui` plugin.
    * - [ ] **PlottingInterface**: A QML component that displays plots and provides an API to be updated.
        * It's installed with `ign-gui` and is not a plugin by itself, similar to [IgnSpinBox](https://github.com/ignitionrobotics/ign-gui/blob/master/include/ignition/gui/qml/IgnSpinBox.qml), but including some C++ logic.
        * Most features should be here, like all the interactions (zoom, hover...), exporting to CSV, etc.
        * This is currently [PlottingInterface](https://github.com/ignitionrobotics/ign-gui/blob/claire/ignition-plotting-tool/include/ignition/gui/qml/PlottingInterface.qml) on @claireyywang 's branch.
    * - [ ] **TopicPlotting**: An `ign-gui` plugin which plots `ign-transport` topics.
        * It uses `PlottingInterface`
        * It accepts topics being dropped from `TransportTopics`.
        * It's a regular `ign-gui` plugin.
        * This is currently [TopicPlotting](https://github.com/ignitionrobotics/ign-gui/tree/claire/ignition-plotting-tool/src/plugins/topic_plotting) on @claireyywang 's branch.
* Ignition Gazebo
    * - [ ] The [ComponentInspector](https://github.com/ignitionrobotics/ign-gazebo/tree/master/src/gui/plugins/component_inspector) needs to be updated so plottable values can be dragged.
    * - [ ] **PlottingTool**: An `ign-gui` plugin which plots `ign-gazebo` components.
        * It uses `PlottingInterface`
        * It accepts components being dropped from `ComponentInspector`.
        * It's an `ign-gazebo` GUI plugin (has access to components).
        * This is currently [PlottingTool](https://github.com/ignitionrobotics/ign-gazebo/tree/claire/ignition-plotting-plugin/src/gui/plugins/plotting_tool) on @claireyywang 's branch.

**Comment by AmrElsersy** [comment]
Happy to work on that issue :D
